Increase Python requirement to 3.6.2
Some error is being thrown about

        from typing import NoReturn, Union
    ImportError: cannot import name 'NoReturn'

which was apparently added in 3.6.2.

https://docs.python.org/3/library/typing.html#typing.NoReturn

and maybe pytest doesn't have the correct dependencies set or something.