Update GitHub Actions and CircleCI
Update CircleCI image to latest cimg

"You’re using a deprecated Docker convenience image. Upgrade to a
next-gen Docker convenience image."

https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034

CircleCI is suggesting to use parallelism

Python 3.11 doesn't work (TODO: debug why).  3.10 works, though.

Update GitHub workflow from starter-workflows:

https://github.com/actions/starter-workflows/blob/main/ci/python-package.yml

Update GitHub Actions Python test versions

"Version 3.6 was not found in the local cache
Error: Version 3.6 with arch x64 not found"