Test Approval invalid input without exceeding bounds
It was previously producing

OverflowError: Python integer -2 out of bounds for uint8

in line

    election = np.asarray(election, dtype=np.uint8)

But we don't actually need to test negative values to test this.